### ISSUE TITLE
macOS problem injecting into slack

### ISSUE THREAD

**Issue by owenworley** [tintinweb/electron-inject#1]
I run the command
`
python -m electron_inject -d -t 60 - /Applications/Slack.app/Contents/MacOS/Slack
`

The result is:

> /Applications/Slack.app/Contents/MacOS/Slack --remote-debugging-port=57356
2018-03-29 11:14:07,454 - DEBUG    - Starting new HTTP connection (1): localhost
2018-03-29 11:14:08,461 - DEBUG    - Starting new HTTP connection (1): localhost
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5
2018-03-29 11:14:08,574 - DEBUG    - http://localhost:57356 "GET /json/list?t=1522318447 HTTP/1.1" 200 5
2018-03-29 11:14:08,575 - DEBUG    - timeout not hit.
Creating Slack Application
2018-03-29 11:14:09,577 - DEBUG    - Starting new HTTP connection (1): localhost
2018-03-29 11:14:09,586 - DEBUG    - http://localhost:57356 "GET /json/list?t=1522318449 HTTP/1.1" 200 4874
2018-03-29 11:14:09,586 - INFO     - injecting hotkeys script into 3cf6736d-a891-43c5-9cbc-1a3355dce8ef
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/electron_inject/__main__.py", line 72, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/electron_inject/__main__.py", line 61, in main
    logger.debug(erb.eval(w, SCRIPT_HOTKEYS_F12_DEVTOOLS_F5_REFRESH))
  File "/usr/local/lib/python2.7/site-packages/electron_inject/__init__.py", line 93, in eval
    ret = json.loads(w['ws'].sendrcv(json.dumps(data)))
  File "/usr/local/lib/python2.7/site-packages/electron_inject/__init__.py", line 41, in sendrcv
    self.send(msg)
  File "/usr/local/lib/python2.7/site-packages/electron_inject/__init__.py", line 35, in send
    return self._connect().send(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/electron_inject/__init__.py", line 31, in _connect
    self.ws = websocket.create_connection(self.url)
AttributeError: 'module' object has no attribute 'create_connection'

**Comment by tintinweb** [comment]
closing this issue. let me know if that still happens and I'll investigate.
