### ISSUE TITLE
UnboundLocalError: local variable 'ce' referenced before assignment

### ISSUE THREAD

**Issue by jnnkB** [tintinweb/electron-inject#3]
I tried it for Whatsapp Web using Python 2.7.15 and Python 3.7.2. Both didn't work probably.

python3
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/electron_inject-0.4-py3.7.egg/electron_inject/__main__.py", line 97, in <module>
  File "/usr/local/lib/python3.7/site-packages/electron_inject-0.4-py3.7.egg/electron_inject/__main__.py", line 76, in main
  File "/usr/local/lib/python3.7/site-packages/electron_inject-0.4-py3.7.egg/electron_inject/__init__.py", line 57, in windows
  File "/usr/local/lib/python3.7/site-packages/electron_inject-0.4-py3.7.egg/electron_inject/__init__.py", line 74, in requests_get
UnboundLocalError: local variable 'ce' referenced before assignment
```
python2
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.macosx-10.14-x86_64/egg/electron_inject/__main__.py", line 97, in <module>
  File "build/bdist.macosx-10.14-x86_64/egg/electron_inject/__main__.py", line 76, in main
  File "build/bdist.macosx-10.14-x86_64/egg/electron_inject/__init__.py", line 57, in windows
  File "build/bdist.macosx-10.14-x86_64/egg/electron_inject/__init__.py", line 74, in requests_get
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=53415): Max retries exceeded with url: /json/list?t=1550338492 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106a37910>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by ciessielski** [comment]
might it be connected somehow with websocket import:
![image](https://user-images.githubusercontent.com/2165282/60722791-33568480-9f32-11e9-99ca-3246223a9ac4.png) ?

**Comment by tintinweb** [comment]
Hi,

@ciessielski - `pip3 install electron_inject` also installs dependencies. otherwise do `pip3 install websocket`
@jnnkB - this only happens if the debugport cannot be reached exceeding the request tries. your app is either very slow or does not accept the debug port cmdline. I've fixed the UnboundLocalError in eb73ff8. the fix is not yet available on pypi as it is only a minor cosmetic fix.

cheers,
tin

**Comment by joveice** [comment]
Does not look like this is fixed in the package on pip.

**Comment by tintinweb** [comment]
> Does not look like this is fixed in the package on pip.

sorry for the delay @joveice. just pushed the fixed version to pypi.

cheers
