### ISSUE TITLE
 Startup failed

### ISSUE THREAD

**Issue by alwans** [tintinweb/electron-inject#5]
```DevTools listening on ws://127.0.0.1:50305/devtools/browser/87a96b34-6f92-43ff-9cbf-724d064a040e
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\electron_inject\__main__.py", line 97, in <module>
    main()
  File "C:\Python27\lib\site-packages\electron_inject\__main__.py", line 76, in main
    for w in (_ for _ in erb.windows() if _['id'] not in windows_visited):
  File "C:\Python27\lib\site-packages\electron_inject\__init__.py", line 57, in windows
    for w in self.requests_get("http://%(host)s:%(port)s/json/list?t=%(ts)d" % params).json():
  File "C:\Python27\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded```

**Comment by tintinweb** [comment]
looks like the electron debug interface was not running. can you verify if the port was actually open?
